### ISSUE TITLE
Server side searching/filtering

### ISSUE THREAD

**Issue by ailisp** [near/devgigsboard#21]
We need a server side, either indexer or using data team's data as a service API to:
- support search, fuzz search, filter by author, filter by label, sorting, and combination of all these
- enhance performance to allow search non top level posts and does not slow down typing in search bar
- remove hacks of current frontend implementation of search/filter/sort combinations
- remove unnecessary "indexes" in contract
- scalable when more posts are added and also more filter / sort requirements are added in future

**Comment by ori-near** [comment]
Hi @ailisp – thanks for identifying this enabler work. As we discussed, can you please create this in the other repo and [triage](https://github.com/near/neardevhub-widgets/blob/main/docs/how-we-work.md#triaging) this ticket (e.g. add any details to make it ready for development, including the enabler epic label and specifying the dependency relationship with #106)? Thank you 🙌.

**Comment by ailisp** [comment]
Superseded by https://github.com/near/neardevhub-widgets/issues/115
