### ISSUE TITLE
Upgrade to near-sdk-rs 4.1 and test functionality

### ISSUE THREAD

**Issue by ailisp** [near/devgigsboard#23]
**Problem**
Currently DevHub contract is using near-sdk-rs 3.x. Several API enhancements have been introduced in 4.0 and security updates will also only update for 4.x so we should update to use near-sdk-rs 4.1.

**User Story**

As a developer, I want to use near-sdk-rs 4.x APIs in develop DevHub contract. Particularly I would like to use `require!` macro and new cross contract API.

**Acceptance Criteria**
- Contract build with dependency near-sdk-rs 4.x in Cargo.toml
- All existing functionalities still work. Can be test by deploying a copy of the contract and try functionalities in the DevHub widgets to hit all `Near.call` and `Near.view`.
- Replace several `if ... panic` to `require!`
- Replace cross contract call into social-db contract with 4.x API, ensure the notification on near social still works

**Comment by gautamprikshit1** [comment]
I would like to work on this one

**Comment by frol** [comment]
I had to revert #26 (see https://github.com/near/neardevhub-contract/commit/8fc1fdd54237c646d16b25cbf5bbd7d84a7a4a49) due to https://github.com/near/neardevhub-contract/pull/26#issuecomment-1581018921.

**Comment by ori-near** [comment]
Hi @frol – Can you please provide an update on this ticket? What's the next step here? Do we need to reassign or change the status?

**Comment by frol** [comment]
It seems that @gautamprikshit1 did not have time to proceed with this issue, so I unassigned him, and if someone is ready to jump on it, learn more in https://github.com/near/neardevhub-contract/pull/26#issuecomment-1581018921

**Comment by jaswinder6991** [comment]
Hi @frol, what is pending in this issue atm?
The list of tasks mentioned here - https://github.com/near/neardevhub-contract/pull/26#issuecomment-1581018921 
and the migrations you have mentioned? (which might be just the Sponsorship token according to you guess?)

**Comment by frol** [comment]
@jaswinder6991 well, by this time it will be easier to start the PR from scratch (just manually port the changes) as rebasing will probably just make things unnecessarily complicated.

**Comment by frol** [comment]
With #46 merged, this issue is unblocked, though I think that instead of trying to rebase #26, it would be easier to re-apply the changes manually. cc @jaswinder6991

**Comment by PiVortex** [comment]
I'm going to take a look at this.

**Comment by PiVortex** [comment]
Please help with this 
See src/respost.rs
The test is failing as the two are not equal in the assert_eq!
Which way should it be structured? Should I reformat to be the same as the expected?
![image](https://github.com/near/neardevhub-contract/assets/124691791/5a919084-ba19-4d6d-a505-45a45da332c3)

**Comment by frol** [comment]
@PiVortex The expected value is correct, the `"post"` value has to be a JSON-encoded string, not a JSON object.

<img width="1157" alt="image" src="https://github.com/near/neardevhub-contract/assets/304265/3bd2be3c-0ed2-461b-94d6-d702fbb76288">

**Comment by frol** [comment]
Resolved in #63.
