### ISSUE TITLE
Update smart contract to reflect latest community design

### ISSUE THREAD

**Issue by ailisp** [near/devgigsboard#27]
**Acceptance Criteria**

- Remove labels field, add tag and handle. There should be only one tag and only one handle
- Add sponsorship boolean. (For frontend) When this set to true, sponsorship type of posts of community's label should be post
- Remove overview_page_markdown and events_page_markdown, add wiki1 and wiki2. Each of the wiki should be optional. When it's turned on, it has a name, e.g. "Overview", and markdown content.
- Telegram handles should be only one
- Deploy a version of the updated contract to testnet, and provide test commands in near-cli

**Comment by near-akaia-root** [comment]
test
