### ISSUE TITLE
Featured community on contract side

### ISSUE THREAD

**Issue by ailisp** [near/devgigsboard#36]
**Problem**
Currently featured community is hard coded. We should add support in contract side to allow configuration of featured community.

**Acceptance Criteria**
- Have a view method to return a list of featured community
- Have a call method, only moderators can call to add/remove a community as featured community

**Comment by jaswinder6991** [comment]
I want to work on this issue. I can also pick the corresponding front end widget issue.

**Comment by jaswinder6991** [comment]
I wrote the code for this and deployed it on testnet and it works fine. Here are some issues I am having?
1. Even after deploying the contract, apparently I am not a moderator so could not add featured communities. Commented that part and moved on for now.
2. I have created two different func for add and remove.
3. I am still new to state migrations of contracts so could use some help there. I could not do a lot of things on testnet, including the BOS widget for devhub homepage, cause lots of components are not available on testnet. (Thinking to raise an issue for it. I think there should be a full testnet support with dummy data for feature developments.)
4. How can I best test this end to end on mainnet. If I deploy my contract on mainnet, should I add dummy data to it and then check if everything works fine in the frontend widget? I know I can write rust tests for this. I am looking for help in end to end flow.
5. Is there already an access controlled moderator widget where I can add the UI for adding and removing featured communities.

**Comment by ailisp** [comment]
Hi @jaswinder6991 Thanks for your work!

1. You can use add_member method to add a team called moderators, then add yourself as moderator (a member of moderators team) on testnet
2. Sounds good!
3. Good point. For widgets you can use bos cli, which will at least deploy every DevHub widgets for you. For data you'll need to manually create several communities and several posts. I think two or three are sufficient for test this feature
4. To e2e test on mainnet, you need to be a moderator, so you can't test on production contract. Therefore you also need to deploy a copy of the contract, add_member, add dummy communities and posts. But you don't need to do that, just e2e test on testnet should be sufficient to prove this works.
5. No. There is one for editing community, but it's for moderators & community admins, you can reference src/gigs-board/entity/community/header.jsx for the pattern, but there is no central place for moderator to config something. Will be great if you can create one.

**Comment by jaswinder6991** [comment]
Created a PR(https://github.com/near/neardevhub-contract/pull/42) to address this.
As suggested to test this on testnet, I deployed all the components on testnet. With deploying this contract, I could successfully fetch featured communities on a BOS widget. 
Here is the test widget: https://test.near.org/devhubopen.testnet/widget/gigs-board.pages.Feed 
For some reason the widget works in Preview mode but on in published. Could use some help here.

**Comment by ailisp** [comment]
Thanks @jaswinder6991 nice work so far! @near-akaia-root Since you have recent success in deploying a version to testnet, could you take a look at his deployment and see what went wrong. Look like he has all widgets and contract is deployed and worked.

**Comment by akaia-shadowfox** [comment]
Working on the issue

**Comment by akaia-shadowfox** [comment]
@jaswinder6991, in this case, "Not a function call expression" error appears because `.map()` is being called on `null`. You should replace `null` with `[]` in `Near.view(contractAccountId, "get_featured_communities") ?? null`

**Comment by jaswinder6991** [comment]
Thanks for the help Akaia, here is the working widget.
https://test.near.org/devhubopen.testnet/widget/gigs-board.pages.Feed

Also to be noted here that my contract is deployed at contract.devhubopen.testnet and widgets deployed by devhubopen.testnet, so I had to hard code the contract address to make the above widget work. In my future iterations (infact to do the changes I am told) I will deploy the contract at the same address too, so that context.widgetSrc fetches the contract address.
I will look at the comments in the PR now @ailisp

**Comment by akaia-shadowfox** [comment]
@jaswinder6991 adding `nearDevGovGigsContractAccountId=contract.devhubopen.testnet` to URL parameters and providing `nearDevGovGigsContractAccountId` constant as the first parameter of `Near.view` should work, so there's no need for hardcoding

For example:

```javascript
const postIds = Near.view(nearDevGovGigsContractAccountId, "get_all_post_ids");
```

**Comment by jaswinder6991** [comment]
Thanks a lot. Here is the updated working widget - https://test.near.org/devhubopen.testnet/widget/gigs-board.pages.Feed?nearDevGovGigsContractAccountId=contract.devhubopen.testnet&nearDevGovGigsWidgetsAccountId=devhubopen.testnet
