### ISSUE TITLE
[Projects] Contract tests for #156

### ISSUE THREAD

**Issue by akaia-shadowfox** [near/devgigsboard#49]
Described in https://github.com/near/neardevhub-contract/pull/45#pullrequestreview-1566452235

**Comment by jaswinder6991** [comment]
Hi @carina-akaia, if you are thinking to write Integration tests. I hope this might help:
https://github.com/near/neardevhub-contract/pull/46

**Comment by ori-near** [comment]
Hi @carina-akaia – is this ticket still relevant given our recent discussion? Also, can you please add an actual description to this ticket and help rationalize the P0 priority assignment? Also per our [How we work](https://github.com/near/neardevhub-widgets/blob/main/docs/how-we-work.md) workflow, triaging should ideally happen with DevHub moderators to reflect our overall product level priorities. 

CC: @ailisp

**Comment by akaia-shadowfox** [comment]
Hi @ori-near, yes, it's still relevant because I've been asked to write tests in order to deliver the contract side changes.

**Comment by ori-near** [comment]
Ok thanks for clarifying – I was just thinking since we've simplified the MVP scope, I'm not sure if all the original tests are still required.

**Comment by ailisp** [comment]
@ori-near The #45 logic is complex and better be tested to ensure correctness and not breaking state invariants. Tests can be mostly avoided if we can delete "one workspace can belong to multiple communities".
