### ISSUE TITLE
Extend contract response for solution posts

### ISSUE THREAD

**Issue by akaia-shadowfox** [near/devgigsboard#60]
The following properties should be presented in post's snapshot:

- `is_funding_requested: bool`
- `amount: Option<Balance>`
- `sponsorship_token: Option<SponsorshipToken>`
- `requested_sponsor: Option<AccountId>`

**Comment by akaia-shadowfox** [comment]
@ori-near please assign this task to me, as I have restricted permissions on this repo

**Comment by ori-near** [comment]
Hi @carina-akaia – can we please only use the [neardevhub-widgets](https://github.com/near/neardevhub-widgets) repo for task management? You can track Contract related PRs in here ... but the issues themselves should ideally all leave in one place.

**Comment by akaia-shadowfox** [comment]
@ori-near Okay, will do. Would you like me to recreate this ticket there as well?

**Comment by ori-near** [comment]
@carina-akaia Yes please

**Comment by akaia-shadowfox** [comment]
Moved to https://github.com/near/neardevhub-widgets/issues/285
