### ISSUE TITLE
Broken migration test

### ISSUE THREAD

**Issue by petersalomonsen** [near/devgigsboard#69]
Because of the addition of `V8` here: https://github.com/near/neardevhub-contract/commit/adadfdc9d71dd62fbeb3dd59b46db7854eceba70#diff-c5a2582b4d03774cddd4cfc553007baa6f3d7fb267544a6df75463bfecb9da7cR513

and not updating the `new` method of [lib.rs](https://github.com/near/neardevhub-contract/blob/main/src/lib.rs#L53) accordingly

the migration test, that downloads the devhub contract from mainnet, initialize it with V7 in the state version, but writes data with V8 implementations.

When it tries to upgrade the contract and run the migration it will try updating from V7 to V8, but since the data is already in V8, and the state version flag is in V7, it will fail with `Cannot deserialize the contract state.: Custom { kind: InvalidData, error: \"Not all bytes read\" }`

**Comment by akaia-shadowfox** [comment]
Fix is on the way
