### ISSUE TITLE
Notifications should pass the post type

### ISSUE THREAD

**Issue by elliotBraem** [near/devgigsboard#73]
This is related to [#505](https://github.com/near/neardevhub-widgets/issues/505) and [#504](https://github.com/near/neardevhub-widgets/issues/504) in neardevhub-widgets repository. The goal is to ensure that the notification links route correctly based on the `postType`.

In the case of a blog, the postType is a "comment" with no parentId... this was a hack to get Blogs out fast. We may also want to explore formally creating a "Blog" type and migrating existing "blogs" to this type.

### Implementation:

1.  Modify  [`notify.rs`](https://github.com/near/neardevhub-contract/blob/bbadebda949d98cdb23e1f2bda22fc625b51a79e/src/notify.rs#L42) to ensure that the `postType` is included alongside the ID in function parameters.

2. Update notify functions calls to pass the post type (comes from post body) 
     - [Reply Notification](https://github.com/near/neardevhub-contract/blob/bbadebda949d98cdb23e1f2bda22fc625b51a79e/src/lib.rs#L189)
     - [Edit Notification](https://github.com/near/neardevhub-contract/blob/bbadebda949d98cdb23e1f2bda22fc625b51a79e/src/lib.rs#L328)
     - [Like Notification](https://github.com/near/neardevhub-contract/blob/bbadebda949d98cdb23e1f2bda22fc625b51a79e/src/lib.rs#L133)
     - [Mention Notification](https://github.com/near/neardevhub-contract/blob/bbadebda949d98cdb23e1f2bda22fc625b51a79e/src/lib.rs#L193)

3. Either resolve "comment" type with no parentId as "blog", or create a blog type and migrate existing posts.

**Comment by Tguntenaar** [comment]
I will pick this up now, I can't assign myself, so if someone can do that for me.

**Comment by Tguntenaar** [comment]
> Either resolve "comment" type with no parentId as "blog", or create a blog type and migrate existing posts.

I've been working on creating a blog type and migrate existing posts, but this turns out to be not that straight forward.
@ailisp I would like to take another look at with you if you've got time to call. But for now I will resolve to staying with comments without a parent id.

**Comment by Tguntenaar** [comment]
Closing this issue since notifications will be fixed by using socialdb for proposals
