### ISSUE TITLE
Addon Cleanup

### ISSUE THREAD

**Issue by elliotBraem** [near/devgigsboard#74]
After implementing the new addon framework, we have some pieces of the [community struct](https://github.com/near/neardevhub-contract/blob/main/src/community/mod.rs) and contract that are no longer used.

This is the current struct:
```rust
pub struct Community {
    pub admins: Vec<AccountId>,
    pub handle: CommunityHandle,
    pub name: String,
    pub tag: String,
    pub description: String,
    pub logo_url: String,
    pub banner_url: String,
    pub bio_markdown: Option<String>,
    pub github_handle: Option<String>,
    pub telegram_handle: Vec<String>,
    pub twitter_handle: Option<String>,
    pub website_url: Option<String>,
    pub github: Option<String>, // remove
    pub board: Option<String>, // remove
    pub wiki1: Option<WikiPage>, //remove
    pub wiki2: Option<WikiPage>, //remove
    pub features: CommunityFeatureFlags, //remove
    pub addons: Vec<CommunityAddOn>,
}
```

We can remove "github", "board", "wiki1", "wiki2", "features".

With these removed, we can also remove some functions:

- [ ] update_community_feature_flags
- [ ] update_community_github
- [ ] update_community_board
- [ ] update_community_wiki1
- [ ] update_community_wiki2

There may be more, I would recommend a thorough search.

**Comment by Tguntenaar** [comment]
I will pick this up right now
