### ISSUE TITLE
Community should only allow one Telegram handle

### ISSUE THREAD

**Issue by elliotBraem** [near/devgigsboard#76]
This is the contract solution to [Telegram is expecting a sequence rather than String #544](https://github.com/near/neardevhub-widgets/issues/544). It may also be resolved with #75.

Currently the Community Struct supports Telegram handle to be an array of strings. This should instead be replaced with a single String.

```rust
pub struct Community {
    pub telegram_handle: Vec<String> -> String
}
```

**Comment by Tguntenaar** [comment]
I can pick this up
